export const collegeObjects = {
collegeObjects:
[
  {index: 0, selected: false, collegeName: 'Alabama A&M University'},
  {index: 1, selected: false, collegeName: 'Alderson Broaddus University'},
  {index: 2, selected: false, collegeName: 'Abilene Christian University'},
  {index: 3, selected: false, collegeName: 'Adelphi University'},
  {index: 4, selected: false, collegeName: 'American International College'},
  {index: 5, selected: false, collegeName: 'University of Alaska System'},
  {index: 6, selected: false, collegeName: 'Alabama State University'},
  {index: 7, selected: false, collegeName: 'University at Albany'},
  {index: 8, selected: false, collegeName: 'Albion College'},
  {index: 9, selected: false, collegeName: 'Alfred University'},
  {index: 10, selected: false, collegeName: 'DeSales University'},
  {index: 11, selected: false, collegeName: 'Alma College'},
  {index: 12, selected: false, collegeName: 'Alverno College'},
  {index: 13, selected: false, collegeName: 'Ambassador College & University'},
  {index: 14, selected: false, collegeName: 'American University Washington D.C.'},
  {index: 15, selected: false, collegeName: 'Amherst College'},
  {index: 16, selected: false, collegeName: 'Andrews University'},
  {index: 17, selected: false, collegeName: 'Angelo State University'},
  {index: 18, selected: false, collegeName: 'Saint Anselm College'},
  {index: 19, selected: false, collegeName: 'Antioch University'},
  {index: 20, selected: false, collegeName: 'Antioch University Los Angeles'},
  {index: 21, selected: false, collegeName: 'Antioch University New England'},
  {index: 22, selected: false, collegeName: 'Appalachian State University'},
  {index: 23, selected: false, collegeName: 'Austin Peay State University'},
  {index: 24, selected: false, collegeName: 'Azusa Pacific University'},
  {index: 25, selected: false, collegeName: 'Aquinas College'},
  {index: 26, selected: false, collegeName: 'Spring Arbor University'},
  {index: 27, selected: false, collegeName: 'Arcadia University'},
  {index: 28, selected: false, collegeName: 'The University of Arizona'},
  {index: 29, selected: false, collegeName: 'Armstrong State University'},
  {index: 30, selected: false, collegeName: 'The Art Institute of Chicago'},
  {index: 31, selected: false, collegeName: 'Ashland University'},
  {index: 32, selected: false, collegeName: 'Ashworth College'},
  {index: 33, selected: false, collegeName: 'Assumption College'},
  {index: 34, selected: false, collegeName: 'Arkansas State University'},
  {index: 35, selected: false, collegeName: 'Arizona State University'},
  {index: 36, selected: false, collegeName: 'Arkansas Tech University'},
  {index: 37, selected: false, collegeName: 'Auburn University'},
  {index: 38, selected: false, collegeName: 'Atlantic Union College'},
  {index: 39, selected: false, collegeName: 'Augustana College'},
  {index: 40, selected: false, collegeName: 'Augsburg College'},
  {index: 41, selected: false, collegeName: 'Augustana College'},
  {index: 42, selected: false, collegeName: 'Auburn University at Montgomery'},
  {index: 43, selected: false, collegeName: 'Aurora University'},
  {index: 44, selected: false, collegeName: 'Averett University'},
  {index: 45, selected: false, collegeName: 'Avila University'},
  {index: 46, selected: false, collegeName: 'Babson College'},
  {index: 47, selected: false, collegeName: 'Baker College'},
  {index: 48, selected: false, collegeName: 'Baker University'},
  {index: 49, selected: false, collegeName: 'Bard College'},
  {index: 50, selected: false, collegeName: 'Barry University'},
  {index: 51, selected: false, collegeName: 'Bastyr University'},
  {index: 52, selected: false, collegeName: 'Bates College'},
  {index: 53, selected: false, collegeName: 'Baylor University'},
  {index: 54, selected: false, collegeName: 'Baptist Bible College & Seminary'},
  {index: 55, selected: false, collegeName: 'Boston College'},
  {index: 56, selected: false, collegeName: 'Baylor College of Medicine'},
  {index: 57, selected: false, collegeName: 'Arcadia University'},
  {index: 58, selected: false, collegeName: 'Belmont University'},
  {index: 59, selected: false, collegeName: 'Beloit College'},
  {index: 60, selected: false, collegeName: 'Benedictine University'},
  {index: 61, selected: false, collegeName: 'Benedictine College'},
  {index: 62, selected: false, collegeName: 'Bennington College'},
  {index: 63, selected: false, collegeName: 'Bentley University'},
  {index: 64, selected: false, collegeName: 'Berea College'},
  {index: 65, selected: false, collegeName: 'University of California, Berkeley'},
  {index: 66, selected: false, collegeName: 'Berklee College of Music'},
  {index: 67, selected: false, collegeName: 'Bethany University'},
  {index: 68, selected: false, collegeName: 'Bethel University Minnesota'},
  {index: 69, selected: false, collegeName: 'Bethel College'},
  {index: 70, selected: false, collegeName: 'Boston Graduate School of Psychoanalysis'},
  {index: 71, selected: false, collegeName: 'Bowling Green State University'},
  {index: 72, selected: false, collegeName: 'Bakke Graduate University'},
  {index: 73, selected: false, collegeName: 'Black Hills State University'},
  {index: 74, selected: false, collegeName: 'Binghamton University'},
  {index: 75, selected: false, collegeName: 'Biola University'},
  {index: 76, selected: false, collegeName: 'Bob Jones University'},
  {index: 77, selected: false, collegeName: 'Bloomsburg University of Pennsylvania'},
  {index: 78, selected: false, collegeName: 'Bluefield State College'},
  {index: 79, selected: false, collegeName: 'Bluffton University'},
  {index: 80, selected: false, collegeName: 'Bowdoin College'},
  {index: 81, selected: false, collegeName: 'Bradley University'},
  {index: 82, selected: false, collegeName: 'Brandeis University'},
  {index: 83, selected: false, collegeName: 'Brenau University'},
  {index: 84, selected: false, collegeName: 'Bridgemont Community & Technical College'},
  {index: 85, selected: false, collegeName: 'University of Bridgeport'},
  {index: 86, selected: false, collegeName: 'Bridgewater College'},
  {index: 87, selected: false, collegeName: 'The College at Brockpor'},
  {index: 88, selected: false, collegeName: 'Brown University'},
  {index: 89, selected: false, collegeName: 'Bryant University'},
  {index: 90, selected: false, collegeName: 'Bryn Mawr College'},
  {index: 91, selected: false, collegeName: 'Birmingham-Southern College'},
  {index: 92, selected: false, collegeName: 'Ball State University'},
  {index: 93, selected: false, collegeName: 'Boston University'},
  {index: 94, selected: false, collegeName: 'Bucknell University'},
  {index: 95, selected: false, collegeName: 'University at Buffalo'},
  {index: 96, selected: false, collegeName: 'Butler University'},
  {index: 97, selected: false, collegeName: 'Buena Vista University'},
  {index: 98, selected: false, collegeName: 'Brigham Young University Provo'},
  {index: 99, selected: false, collegeName: 'Brigham Young University Hawaii'},
  {index: 100, selected: false, collegeName: 'Brigham Young University Idaho'},
  {index: 101, selected: false, collegeName: 'California Lutheran University'},
  {index: 102, selected: false, collegeName: 'California Polytechnic State University, San Luis Obispo'},
  {index: 103, selected: false, collegeName: 'The California State University'},
  {index: 104, selected: false, collegeName: 'California State University, Los Angeles'},
  {index: 105, selected: false, collegeName: 'Caltech'},
  {index: 106, selected: false, collegeName: 'California University of Pennsylvania'},
  {index: 107, selected: false, collegeName: 'Calvin College'},
  {index: 108, selected: false, collegeName: 'Claremont Graduate University'},
  {index: 109, selected: false, collegeName: 'Cameron University'},
  {index: 110, selected: false, collegeName: 'Campbell University'},
  {index: 111, selected: false, collegeName: 'Canisius College'},
  {index: 112, selected: false, collegeName: 'Carleton College'},
  {index: 113, selected: false, collegeName: 'Carlow University'},
  {index: 114, selected: false, collegeName: 'Carroll College'},
  {index: 115, selected: false, collegeName: 'Carthage College'},
  {index: 116, selected: false, collegeName: 'Christian Brothers University'},
  {index: 117, selected: false, collegeName: 'Carrington College'},
  {index: 118, selected: false, collegeName: 'Colorado Christian University'},
  {index: 119, selected: false, collegeName: 'Cedarville University'},
  {index: 120, selected: false, collegeName: 'Centenary College of Louisiana'},
  {index: 121, selected: false, collegeName: 'Central College'},
  {index: 122, selected: false, collegeName: 'Centre College'},
  {index: 123, selected: false, collegeName: 'Champlain College'},
  {index: 124, selected: false, collegeName: 'Chapman University'},
  {index: 125, selected: false, collegeName: 'Chatham University'},
  {index: 126, selected: false, collegeName: 'Chesapeake College'},
  {index: 127, selected: false, collegeName: 'Cheyney University of Pennsylvania'},
  {index: 128, selected: false, collegeName: 'The Citadel'},
  {index: 129, selected: false, collegeName: 'City University of Seattle'},
  {index: 130, selected: false, collegeName: 'Clarion University of Pennsylvania'},
  {index: 131, selected: false, collegeName: 'Clarke University'},
  {index: 132, selected: false, collegeName: 'Clarkson University'},
  {index: 133, selected: false, collegeName: 'Clark University'},
  {index: 134, selected: false, collegeName: 'Clemson University, South Carolina'},
  {index: 135, selected: false, collegeName: 'Claremont McKenna College'},
  {index: 136, selected: false, collegeName: 'Central Michigan University'},
  {index: 137, selected: false, collegeName: 'Carnegie Mellon University'},
  {index: 138, selected: false, collegeName: 'Carson-Newman University'},
  {index: 139, selected: false, collegeName: 'Christopher Newport University'},
  {index: 140, selected: false, collegeName: 'California National University'},
  {index: 141, selected: false, collegeName: 'College of the Atlantic'},
  {index: 142, selected: false, collegeName: 'Coastal Carolina University'},
  {index: 143, selected: false, collegeName: 'State University of New York Cobleskill'},
  {index: 144, selected: false, collegeName: 'Coe College'},
  {index: 145, selected: false, collegeName: 'College of Charleston'},
  {index: 146, selected: false, collegeName: 'Coker College'},
  {index: 147, selected: false, collegeName: 'Colby College'},
  {index: 148, selected: false, collegeName: 'Colgate University'},
  {index: 149, selected: false, collegeName: 'University of Colorado Boulder'},
  {index: 150, selected: false, collegeName: 'Colorado State University'},
  {index: 151, selected: false, collegeName: 'Columbia Southern University'},
  {index: 152, selected: false, collegeName: 'Columbia College Chicago'},
  {index: 153, selected: false, collegeName: 'Columbia University in the City of New York'},
  {index: 154, selected: false, collegeName: 'Concord University'},
  {index: 155, selected: false, collegeName: 'Connecticut College'},
  {index: 156, selected: false, collegeName: 'Cooper Union'},
  {index: 157, selected: false, collegeName: 'Concordia College'},
  {index: 158, selected: false, collegeName: 'Cornell University'},
  {index: 159, selected: false, collegeName: 'Cornell College'},
  {index: 160, selected: false, collegeName: 'State University of New York Cortland'},
  {index: 161, selected: false, collegeName: 'California State Polytechnic University, Pomona'},
  {index: 162, selected: false, collegeName: 'Creighton University'},
  {index: 163, selected: false, collegeName: 'University of Minnesota, Crookston'},
  {index: 164, selected: false, collegeName: 'College of Saint Benedict & Saint John\'s University'},
  {index: 165, selected: false, collegeName: 'Chadron State College'},
  {index: 166, selected: false, collegeName: 'Castleton State College of Vermont'},
  {index: 167, selected: false, collegeName: 'Concordia University, St. Paul'},
  {index: 168, selected: false, collegeName: 'The College of St. Scholastica'},
  {index: 169, selected: false, collegeName: 'California State University, Chico'},
  {index: 170, selected: false, collegeName: 'California State University, Dominguez Hills'},
  {index: 171, selected: false, collegeName: 'California State University, East Bay'},
  {index: 172, selected: false, collegeName: 'California State University, Fresno'},
  {index: 173, selected: false, collegeName: 'California State University, East Bay'},
  {index: 174, selected: false, collegeName: 'California State University, Long Beach'},
  {index: 175, selected: false, collegeName: 'California State University, Monterey Bay'},
  {index: 176, selected: false, collegeName: 'California State University, Northridge'},
  {index: 177, selected: false, collegeName: 'Cleveland State University'},
  {index: 178, selected: false, collegeName: 'California State University, Sacramento'},
  {index: 179, selected: false, collegeName: 'California State University, San Bernardino'},
  {index: 180, selected: false, collegeName: 'California State University, San Marcos'},
  {index: 181, selected: false, collegeName: 'California State University Stanislaus'},
  {index: 182, selected: false, collegeName: 'Christian Theological Seminary'},
  {index: 183, selected: false, collegeName: 'The Catholic University of America'},
  {index: 184, selected: false, collegeName: 'The City University of New York'},
  {index: 185, selected: false, collegeName: 'Curry College'},
  {index: 186, selected: false, collegeName: 'Case Western Reserve University'},
  {index: 187, selected: false, collegeName: 'Central Washington University'},
  {index: 188, selected: false, collegeName: 'University of Minnesota Duluth'},
  {index: 189, selected: false, collegeName: 'Daemen College'},
  {index: 190, selected: false, collegeName: 'Dartmouth College'},
  {index: 191, selected: false, collegeName: 'Davenport University'},
  {index: 192, selected: false, collegeName: 'Davidson College'},
  {index: 193, selected: false, collegeName: 'University of Dubuque'},
  {index: 194, selected: false, collegeName: 'Dallas Baptist University'},
  {index: 195, selected: false, collegeName: 'Delta State University'},
  {index: 196, selected: false, collegeName: 'Denison University'},
  {index: 197, selected: false, collegeName: 'DePaul University'},
  {index: 198, selected: false, collegeName: 'DePauw University'},
  {index: 199, selected: false, collegeName: 'DeSales University'},
  {index: 200, selected: false, collegeName: 'DeVry University'},
  {index: 201, selected: false, collegeName: 'Dickinson College'},
  {index: 202, selected: false, collegeName: 'Dillard University'},
  {index: 203, selected: false, collegeName: 'Dixie State University'},
  {index: 204, selected: false, collegeName: 'Dominican University of California'},
  {index: 205, selected: false, collegeName: 'Dordt College'},
  {index: 206, selected: false, collegeName: 'Dowling College Long Island'},
  {index: 207, selected: false, collegeName: 'Drake University'},
  {index: 208, selected: false, collegeName: 'Drew University'},
  {index: 209, selected: false, collegeName: 'Drexel University'},
  {index: 210, selected: false, collegeName: 'Drury University'},
  {index: 211, selected: false, collegeName: 'Dakota State University'},
  {index: 212, selected: false, collegeName: 'University of Denver'},
  {index: 213, selected: false, collegeName: 'Duke University'},
  {index: 214, selected: false, collegeName: 'Duquesne University'},
  {index: 215, selected: false, collegeName: 'Daniel Webster College'},
  {index: 216, selected: false, collegeName: 'Dakota Wesleyan University'},
  {index: 217, selected: false, collegeName: 'Earlham College'},
  {index: 218, selected: false, collegeName: 'Eastern West Virginia Community & Technical College'},
  {index: 219, selected: false, collegeName: 'East Central University'},
  {index: 220, selected: false, collegeName: 'Elizabeth City State University'},
  {index: 221, selected: false, collegeName: 'East Carolina University'},
  {index: 222, selected: false, collegeName: 'Edgewood College'},
  {index: 223, selected: false, collegeName: 'Edinboro University'},
  {index: 224, selected: false, collegeName: 'Eastern Illinois University'},
  {index: 225, selected: false, collegeName: 'Eastern Kentucky University'},
  {index: 226, selected: false, collegeName: 'Elmhurst College'},
  {index: 227, selected: false, collegeName: 'Elon University'},
  {index: 228, selected: false, collegeName: 'Emerson College'},
  {index: 229, selected: false, collegeName: 'Eastern Michigan University'},
  {index: 230, selected: false, collegeName: 'Emmanuel College'},
  {index: 231, selected: false, collegeName: 'Emory University'},
  {index: 232, selected: false, collegeName: 'Emporia State University'},
  {index: 233, selected: false, collegeName: 'Eastern Mennonite University'},
  {index: 234, selected: false, collegeName: 'Eastern New Mexico University'},
  {index: 235, selected: false, collegeName: 'Embry-Riddle Aeronautical University'},
  {index: 236, selected: false, collegeName: 'State University of New York College of Environmental Science and Forestry'},
  {index: 237, selected: false, collegeName: 'East Stroudsburg University'},
  {index: 238, selected: false, collegeName: 'Elizabethtown College'},
  {index: 239, selected: false, collegeName: 'East Tennessee State University'},
  {index: 240, selected: false, collegeName: 'University of Evansville'},
  {index: 241, selected: false, collegeName: 'The Evergreen State College'},
  {index: 242, selected: false, collegeName: 'Eastern Washington University'},
  {index: 243, selected: false, collegeName: 'Fairmont State University'},
  {index: 244, selected: false, collegeName: 'Florida Agricultural and Mechanical University'},
  {index: 245, selected: false, collegeName: 'Franklin & Marshall College'},
  {index: 246, selected: false, collegeName: 'Farmingdale State College'},
  {index: 247, selected: false, collegeName: 'Florida Atlantic University'},
  {index: 248, selected: false, collegeName: 'Fairleigh Dickinson University'},
  {index: 249, selected: false, collegeName: 'Ferris State University'},
  {index: 250, selected: false, collegeName: 'Florida Gulf Coast University'},
  {index: 251, selected: false, collegeName: 'Fort Hays State University'},
  {index: 252, selected: false, collegeName: 'Fielding Graduate University'},
  {index: 253, selected: false, collegeName: 'Fisk University'},
  {index: 254, selected: false, collegeName: 'Florida Institute of Technology'},
  {index: 255, selected: false, collegeName: 'Florida International University'},
  {index: 256, selected: false, collegeName: 'Fontbonne University'},
  {index: 257, selected: false, collegeName: 'Fordham University'},
  {index: 258, selected: false, collegeName: 'Fort Lewis College'},
  {index: 259, selected: false, collegeName: 'Franklin University'},
  {index: 260, selected: false, collegeName: 'Fredonia State University of New York'},
  {index: 261, selected: false, collegeName: 'Fresno Pacific University'},
  {index: 262, selected: false, collegeName: 'Friends University'},
  {index: 263, selected: false, collegeName: 'Florida State University'},
  {index: 264, selected: false, collegeName: 'Fuller Theological Seminary'},
  {index: 265, selected: false, collegeName: 'California State University, Fullerton'},
  {index: 266, selected: false, collegeName: 'Furman University'},
  {index: 267, selected: false, collegeName: 'Gustavus Adolphus College'},
  {index: 268, selected: false, collegeName: 'Gallaudet University'},
  {index: 269, selected: false, collegeName: 'Gannon University'},
  {index: 270, selected: false, collegeName: 'Georgia Institute of Technology'},
  {index: 271, selected: false, collegeName: 'Goldey-Beacom College'},
  {index: 272, selected: false, collegeName: 'State University of New York Geneseo'},
  {index: 273, selected: false, collegeName: 'Geneva College'},
  {index: 274, selected: false, collegeName: 'Georgetown University'},
  {index: 275, selected: false, collegeName: 'Georgian Court University'},
  {index: 276, selected: false, collegeName: 'Gettysburg College'},
  {index: 277, selected: false, collegeName: 'Golden Gate University'},
  {index: 278, selected: false, collegeName: 'Glenville State College'},
  {index: 279, selected: false, collegeName: 'Global University'},
  {index: 280, selected: false, collegeName: 'George Mason University'},
  {index: 281, selected: false, collegeName: 'Gonzaga University'},
  {index: 282, selected: false, collegeName: 'Goshen College'},
  {index: 283, selected: false, collegeName: 'Goucher College'},
  {index: 284, selected: false, collegeName: 'Grace College & Theological Seminary in Indiana'},
  {index: 285, selected: false, collegeName: 'Graceland University'},
  {index: 286, selected: false, collegeName: 'Greenleaf University Online Degree Programs'},
  {index: 287, selected: false, collegeName: 'Georgia State University'},
  {index: 288, selected: false, collegeName: 'Guilford College'},
  {index: 289, selected: false, collegeName: 'Grand Valley State University'},
  {index: 290, selected: false, collegeName: 'The George Washington University'},
  {index: 291, selected: false, collegeName: 'Hamilton College'},
  {index: 292, selected: false, collegeName: 'Hamline University'},
  {index: 293, selected: false, collegeName: 'Hampshire College'},
  {index: 294, selected: false, collegeName: 'Hampton University'},
  {index: 295, selected: false, collegeName: 'Hanover College'},
  {index: 296, selected: false, collegeName: 'Harding University'},
  {index: 297, selected: false, collegeName: 'University of Hartford'},
  {index: 298, selected: false, collegeName: 'Hartwick College'},
  {index: 299, selected: false, collegeName: 'Harvard University'},
  {index: 300, selected: false, collegeName: 'Haskell Indian Nations University'},
  {index: 301, selected: false, collegeName: 'Hastings College'},
  {index: 302, selected: false, collegeName: 'Haverford College'},
  {index: 303, selected: false, collegeName: 'University of Hawaii System'},
  {index: 304, selected: false, collegeName: 'Heidelberg University'},
  {index: 305, selected: false, collegeName: 'Hendrix College'},
  {index: 306, selected: false, collegeName: 'Hesston College'},
  {index: 307, selected: false, collegeName: 'High Point University'},
  {index: 308, selected: false, collegeName: 'Hillsdale College'},
  {index: 309, selected: false, collegeName: 'Hiram College'},
  {index: 310, selected: false, collegeName: 'Harvey Mudd College'},
  {index: 311, selected: false, collegeName: 'Harvey Mudd College'},
  {index: 312, selected: false, collegeName: 'Hofstra University'},
  {index: 313, selected: false, collegeName: 'Hollins University'},
  {index: 314, selected: false, collegeName: 'College of the Holy Cross'},
  {index: 315, selected: false, collegeName: 'Hood College'},
  {index: 316, selected: false, collegeName: 'Hope College'},
  {index: 317, selected: false, collegeName: 'Howard University'},
  {index: 318, selected: false, collegeName: 'Hawaii Pacific University'},
  {index: 319, selected: false, collegeName: 'Hampden-Sydney College'},
  {index: 320, selected: false, collegeName: 'University of North Texas Health Science Center'},
  {index: 321, selected: false, collegeName: 'Humboldt State University'},
  {index: 322, selected: false, collegeName: 'Hunter College'},
  {index: 323, selected: false, collegeName: 'Huntingdon College'},
  {index: 324, selected: false, collegeName: 'Hobart and William Smith Colleges'},
  {index: 325, selected: false, collegeName: 'Iowa State University'},
  {index: 326, selected: false, collegeName: 'Illinois Benedictine College'},
  {index: 327, selected: false, collegeName: 'ICI University'},
  {index: 328, selected: false, collegeName: 'Illinois Institute of Technology'},
  {index: 329, selected: false, collegeName: 'Illinois State University'},
  {index: 330, selected: false, collegeName: 'Illinois State University'},
  {index: 331, selected: false, collegeName: 'Indiana University'},
  {index: 332, selected: false, collegeName: 'Indiana State University'},
  {index: 333, selected: false, collegeName: 'Indiana Wesleyan University'},
  {index: 334, selected: false, collegeName: 'Iona College'},
  {index: 335, selected: false, collegeName: 'Idaho State University'},
  {index: 336, selected: false, collegeName: 'Ithaca College'},
  {index: 337, selected: false, collegeName: 'Indiana University of Pennsylvania'},
  {index: 338, selected: false, collegeName: 'Indiana University-Purdue University Indianapolis'},
  {index: 339, selected: false, collegeName: 'John Brown University'},
  {index: 340, selected: false, collegeName: 'University of Jamestown'},
  {index: 341, selected: false, collegeName: 'Johnson C. Smith University'},
  {index: 342, selected: false, collegeName: 'Thomas Jefferson University'},
  {index: 343, selected: false, collegeName: 'William Jewell College'},
  {index: 344, selected: false, collegeName: 'John F. Kennedy University'},
  {index: 345, selected: false, collegeName: 'Johns Hopkins University'},
  {index: 346, selected: false, collegeName: 'James Madison University'},
  {index: 347, selected: false, collegeName: 'Jones College'},
  {index: 348, selected: false, collegeName: 'Jacksonville State University'},
  {index: 349, selected: false, collegeName: 'Jackson State University'},
  {index: 350, selected: false, collegeName: 'The Jewish Theological Seminary'},
  {index: 351, selected: false, collegeName: 'Jacksonville University'},
  {index: 352, selected: false, collegeName: 'Judson College'},
  {index: 353, selected: false, collegeName: 'Juniata College'},
  {index: 354, selected: false, collegeName: 'Johnson & Wales University'},
  {index: 355, selected: false, collegeName: 'Kaplan University'},
  {index: 356, selected: false, collegeName: 'Kansas City University of Medicine and Biosciences'},
  {index: 357, selected: false, collegeName: 'Kean University'},
  {index: 358, selected: false, collegeName: 'Keene State College'},
  {index: 359, selected: false, collegeName: 'Kent State University'},
  {index: 360, selected: false, collegeName: 'Kenyon College'},
  {index: 361, selected: false, collegeName: 'Keck Graduat Institute'},
  {index: 362, selected: false, collegeName: 'King\'s College'},
  {index: 363, selected: false, collegeName: 'Knox College'},
  {index: 364, selected: false, collegeName: 'Kansas State University'},
  {index: 365, selected: false, collegeName: 'The University of Kansas'},
  {index: 366, selected: false, collegeName: 'University of Kansas Medical Center'},
  {index: 367, selected: false, collegeName: 'Kutztown University'},
  {index: 368, selected: false, collegeName: 'Kanawha Valley Community and Technical College'},
  {index: 369, selected: false, collegeName: 'Kansas Wesleyan University'},
  {index: 370, selected: false, collegeName: 'Kalamazoo College'},
  {index: 371, selected: false, collegeName: 'Louisiana College'},
  {index: 372, selected: false, collegeName: 'Lafayette College'},
  {index: 373, selected: false, collegeName: 'Lamar University'},
  {index: 374, selected: false, collegeName: 'Langston University'},
  {index: 375, selected: false, collegeName: 'La Salle University'},
  {index: 376, selected: false, collegeName: 'La Sierra University'},
  {index: 377, selected: false, collegeName: 'Louisiana Tech University'},
  {index: 378, selected: false, collegeName: 'University of La Verne'},
  {index: 379, selected: false, collegeName: 'Lawrence University'},
  {index: 380, selected: false, collegeName: 'Lewis & Clark'},
  {index: 381, selected: false, collegeName: 'Lewis-Clark State College'},
  {index: 382, selected: false, collegeName: 'Lehigh University'},
  {index: 383, selected: false, collegeName: 'Le Moyne College'},
  {index: 384, selected: false, collegeName: 'LeTourneau University'},
  {index: 385, selected: false, collegeName: 'Lewis University'},
  {index: 386, selected: false, collegeName: 'Lake Forest College'},
  {index: 387, selected: false, collegeName: 'Lock Haven University'},
  {index: 388, selected: false, collegeName: 'Liberty University Christian College Education'},
  {index: 389, selected: false, collegeName: 'The Lincoln University'},
  {index: 390, selected: false, collegeName: 'Linfield College'},
  {index: 391, selected: false, collegeName: 'Linn-Benton Community College'},
  {index: 392, selected: false, collegeName: 'Long Island University'},
  {index: 393, selected: false, collegeName: 'Loma Linda University'},
  {index: 394, selected: false, collegeName: 'Loyola Marymount University'},
  {index: 395, selected: false, collegeName: 'Loras College'},
  {index: 396, selected: false, collegeName: 'University of Louisville'},
  {index: 397, selected: false, collegeName: 'Loyola University Maryland'},
  {index: 398, selected: false, collegeName: 'Lyndon State College, Vermont'},
  {index: 399, selected: false, collegeName: 'Lake Superior State University'},
  {index: 400, selected: false, collegeName: 'Louisiana State University'},
  {index: 401, selected: false, collegeName: 'Louisiana State University at Alexandria'},
  {index: 402, selected: false, collegeName: 'Lawrence Technological University'},
  {index: 403, selected: false, collegeName: 'Loyola University Chicago'},
  {index: 404, selected: false, collegeName: 'Langston University'},
  {index: 405, selected: false, collegeName: 'Luther College'},
  {index: 406, selected: false, collegeName: 'Luther Seminary'},
  {index: 407, selected: false, collegeName: 'Lebanon Valley College'},
  {index: 408, selected: false, collegeName: 'Lake Washington Institute of Technology'},
  {index: 409, selected: false, collegeName: 'Lycoming College'},
  {index: 410, selected: false, collegeName: 'Lynchburg College'},
  {index: 411, selected: false, collegeName: 'Lyon College'},
  {index: 412, selected: false, collegeName: 'Macalester College'},
  {index: 413, selected: false, collegeName: 'University of Maine System'},
  {index: 414, selected: false, collegeName: 'Malone University'},
  {index: 415, selected: false, collegeName: 'Manhattan College'},
  {index: 416, selected: false, collegeName: 'Marietta College'},
  {index: 417, selected: false, collegeName: 'Marist College'},
  {index: 418, selected: false, collegeName: 'Marlboro College'},
  {index: 419, selected: false, collegeName: 'Marshall University'},
  {index: 420, selected: false, collegeName: 'Marymount University'},
  {index: 421, selected: false, collegeName: 'University of Massachusetts'},
  {index: 422, selected: false, collegeName: 'Mary Baldwin College'},
  {index: 423, selected: false, collegeName: 'Mississippi College'},
  {index: 424, selected: false, collegeName: 'Minneapolis College of Art and Design'},
  {index: 425, selected: false, collegeName: 'McNeese State University'},
  {index: 426, selected: false, collegeName: 'Mountwest Community & Technical College'},
  {index: 427, selected: false, collegeName: 'Medical College of Wisconsin'},
  {index: 428, selected: false, collegeName: 'The University of Memphis'},
  {index: 429, selected: false, collegeName: 'Mercy College'},
  {index: 430, selected: false, collegeName: 'Meredith College'},
  {index: 431, selected: false, collegeName: 'Messiah College'},
  {index: 432, selected: false, collegeName: 'University of Miami'},
  {index: 433, selected: false, collegeName: 'Middlebury College'},
  {index: 434, selected: false, collegeName: 'Millersville University'},
  {index: 435, selected: false, collegeName: 'Millikin University'},
  {index: 436, selected: false, collegeName: 'Millsaps College'},
  {index: 437, selected: false, collegeName: 'Minot State University'},
  {index: 438, selected: false, collegeName: 'University of Missouri'},
  {index: 439, selected: false, collegeName: 'Minot State University'},
  {index: 440, selected: false, collegeName: 'Massachusetts Institute of Technology'},
  {index: 441, selected: false, collegeName: 'Mansfield University of Pennsylvania'},
  {index: 442, selected: false, collegeName: 'Molloy College'},
  {index: 443, selected: false, collegeName: 'Monmouth College'},
  {index: 444, selected: false, collegeName: 'Monmouth University'},
  {index: 445, selected: false, collegeName: 'Montana State University'},
  {index: 446, selected: false, collegeName: 'Montclair State University'},
  {index: 447, selected: false, collegeName: 'California State University, Monterey Bay'},
  {index: 448, selected: false, collegeName: 'Montreat College'},
  {index: 449, selected: false, collegeName: 'Moravian College'},
  {index: 450, selected: false, collegeName: 'Morgan State University'},
  {index: 451, selected: false, collegeName: 'University of Minnesota, Morris'},
  {index: 452, selected: false, collegeName: 'Mount Saint Joseph High School'},
  {index: 453, selected: false, collegeName: 'Mount Saint Mary College, Newburgh'},
  {index: 454, selected: false, collegeName: 'Milwaukee School of Engineering'},
  {index: 455, selected: false, collegeName: 'Mississippi State University'},
  {index: 456, selected: false, collegeName: 'Missouri Southern State University'},
  {index: 457, selected: false, collegeName: 'Michigan State University'},
  {index: 458, selected: false, collegeName: 'Montana State University Billings'},
  {index: 459, selected: false, collegeName: 'Montana Tech of the University of Montana'},
  {index: 460, selected: false, collegeName: 'Mount Holyoke College'},
  {index: 461, selected: false, collegeName: 'Middle Tennessee State University'},
  {index: 462, selected: false, collegeName: 'Michigan Technological University'},
  {index: 463, selected: false, collegeName: 'Marquette University'},
  {index: 464, selected: false, collegeName: 'Maharishi University of Management'},
  {index: 465, selected: false, collegeName: 'Miami University'},
  {index: 466, selected: false, collegeName: 'Muskingum University'},
  {index: 467, selected: false, collegeName: 'Mississippi University for Women'},
  {index: 468, selected: false, collegeName: 'Midwestern State University'},
  {index: 469, selected: false, collegeName: 'Northern Arizona University'},
  {index: 470, selected: false, collegeName: 'Nazareth College'},
  {index: 471, selected: false, collegeName: 'North Carolina A&T State University'},
  {index: 472, selected: false, collegeName: 'North Central University'},
  {index: 473, selected: false, collegeName: 'North Carolina Central University'},
  {index: 474, selected: false, collegeName: 'North Carolina State University'},
  {index: 475, selected: false, collegeName: 'North Carolina Wesleyan College'},
  {index: 476, selected: false, collegeName: 'University of Notre Dame'},
  {index: 477, selected: false, collegeName: 'North Dakota State University'},
  {index: 478, selected: false, collegeName: 'National Defense University'},
  {index: 479, selected: false, collegeName: 'Newberry College'},
  {index: 480, selected: false, collegeName: 'New College of California'},
  {index: 481, selected: false, collegeName: 'University of New Haven'},
  {index: 482, selected: false, collegeName: 'State University of New York at New Paltz'},
  {index: 483, selected: false, collegeName: 'Niagara University'},
  {index: 484, selected: false, collegeName: 'Northern Illinois University'},
  {index: 485, selected: false, collegeName: 'New Jersey Institute of Technology'},
  {index: 486, selected: false, collegeName: 'Northern Kentucky University'},
  {index: 487, selected: false, collegeName: 'National Louis University'},
  {index: 488, selected: false, collegeName: 'New Mexico Highlands University'},
  {index: 489, selected: false, collegeName: 'New Mexico State University'},
  {index: 490, selected: false, collegeName: 'New Mexico Institute of Mining and Technology'},
  {index: 491, selected: false, collegeName: 'Northern Michigan University'},
  {index: 492, selected: false, collegeName: 'Northeastern University'},
  {index: 493, selected: false, collegeName: 'Northern State University'},
  {index: 494, selected: false, collegeName: 'Northland College'},
  {index: 495, selected: false, collegeName: 'Norwich University'},
  {index: 496, selected: false, collegeName: 'Nova Southeastern University'},
  {index: 497, selected: false, collegeName: 'Norfolk State University'},
  {index: 498, selected: false, collegeName: 'Northwestern State University of Louisiana'},
  {index: 499, selected: false, collegeName: 'Northeastern State University'},
  {index: 500, selected: false, collegeName: 'Walden University'},
  {index: 501, selected: false, collegeName: 'National University'},
  {index: 502, selected: false, collegeName: 'Northwestern College'},
  {index: 503, selected: false, collegeName: 'Northwest Missouri State University'},
  {index: 504, selected: false, collegeName: 'New York Institute of Technology'},
  {index: 505, selected: false, collegeName: 'New York University'},
  {index: 506, selected: false, collegeName: 'Oakland University'},
  {index: 507, selected: false, collegeName: 'Oberlin College & Conservatory'},
  {index: 508, selected: false, collegeName: 'Old Dominion University'},
  {index: 509, selected: false, collegeName: 'Oregon Health & Science University'},
  {index: 510, selected: false, collegeName: 'The Ohio State University'},
  {index: 511, selected: false, collegeName: 'Ohio University'},
  {index: 512, selected: false, collegeName: 'Oregon Health & Science University'},
  {index: 513, selected: false, collegeName: 'Oklahoma Baptist University'},
  {index: 514, selected: false, collegeName: 'Oklahoma City University'},
  {index: 515, selected: false, collegeName: 'Oklahoma State University'},
  {index: 516, selected: false, collegeName: 'University of Mississippi'},
  {index: 517, selected: false, collegeName: 'Olivet Nazarene University'},
  {index: 518, selected: false, collegeName: 'Our Lady of the Lake University'},
  {index: 519, selected: false, collegeName: 'Ohio Northern University'},
  {index: 520, selected: false, collegeName: 'Oregon State University'},
  {index: 521, selected: false, collegeName: 'Oregon State University'},
  {index: 522, selected: false, collegeName: 'Oral Roberts University'},
  {index: 523, selected: false, collegeName: 'The Ohio State University'},
  {index: 524, selected: false, collegeName: 'State University of New York At Oswego'},
  {index: 525, selected: false, collegeName: 'Otterbein University'},
  {index: 526, selected: false, collegeName: 'Ohio Wesleyan University'},
  {index: 527, selected: false, collegeName: 'Occidental College'},
  {index: 528, selected: false, collegeName: 'University of the Ozarks'},
  {index: 529, selected: false, collegeName: 'Pace University'},
  {index: 530, selected: false, collegeName: 'Pacific University'},
  {index: 531, selected: false, collegeName: 'The University of Texas-Pan American'},
  {index: 532, selected: false, collegeName: 'Pensacola Christian College'},
  {index: 533, selected: false, collegeName: 'Portland State University'},
  {index: 534, selected: false, collegeName: 'William Peace University'},
  {index: 535, selected: false, collegeName: 'Pepperdine University'},
  {index: 536, selected: false, collegeName: 'Peru State College'},
  {index: 537, selected: false, collegeName: 'Phillips University'},
  {index: 538, selected: false, collegeName: 'University of Phoenix'},
  {index: 539, selected: false, collegeName: 'Pierpont Community & Technical College'},
  {index: 540, selected: false, collegeName: 'University of Pittsburgh'},
  {index: 541, selected: false, collegeName: 'Pittsburg State University'},
  {index: 542, selected: false, collegeName: 'Pitzer College'},
  {index: 543, selected: false, collegeName: 'Platt College'},
  {index: 544, selected: false, collegeName: 'State University of New York Plattsburgh'},
  {index: 545, selected: false, collegeName: 'Pacific Lutheran University'},
  {index: 546, selected: false, collegeName: 'Plymouth State University'},
  {index: 547, selected: false, collegeName: 'NYU Polytechnic School of Engineering'},
  {index: 548, selected: false, collegeName: 'Pomona College'},
  {index: 549, selected: false, collegeName: 'Potomac State College'},
  {index: 550, selected: false, collegeName: 'The State University of New York at Potsdam'},
  {index: 551, selected: false, collegeName: 'Pratt Institute'},
  {index: 552, selected: false, collegeName: 'Presbyterian College'},
  {index: 553, selected: false, collegeName: 'Princeton University'},
  {index: 554, selected: false, collegeName: 'Providence College'},
  {index: 555, selected: false, collegeName: 'Pennsylvania State University'},
  {index: 556, selected: false, collegeName: 'Pacific Union College'},
  {index: 557, selected: false, collegeName: 'Polytechnic University of Puerto Rico'},
  {index: 558, selected: false, collegeName: 'Purdue University'},
  {index: 559, selected: false, collegeName: 'Prairie View A&M University'},
  {index: 560, selected: false, collegeName: 'Quincy University'},
  {index: 561, selected: false, collegeName: 'Quinnipiac University Connecticut'},
  {index: 562, selected: false, collegeName: 'Radford University'},
  {index: 563, selected: false, collegeName: 'Ramapo College of New Jersey'},
  {index: 564, selected: false, collegeName: 'Reed College'},
  {index: 565, selected: false, collegeName: 'Regent University'},
  {index: 566, selected: false, collegeName: 'Regis University'},
  {index: 567, selected: false, collegeName: 'Rhodes College'},
  {index: 568, selected: false, collegeName: 'Rhode Island College'},
  {index: 569, selected: false, collegeName: 'Rice University'},
  {index: 570, selected: false, collegeName: 'Rider University'},
  {index: 571, selected: false, collegeName: 'Ripon College'},
  {index: 572, selected: false, collegeName: 'Rochester Institute of Technology'},
  {index: 573, selected: false, collegeName: 'Randolph-Macon College'},
  {index: 574, selected: false, collegeName: 'Roanoke College'},
  {index: 575, selected: false, collegeName: 'University of Rochester'},
  {index: 576, selected: false, collegeName: 'The Rockefeller University'},
  {index: 577, selected: false, collegeName: 'Rockford University'},
  {index: 578, selected: false, collegeName: 'Rockhurst University'},
  {index: 579, selected: false, collegeName: 'Rocky Mountain College'},
  {index: 580, selected: false, collegeName: 'Rollins College'},
  {index: 581, selected: false, collegeName: 'Rose-Hulman Institute of Technology'},
  {index: 582, selected: false, collegeName: 'Rowan University'},
  {index: 583, selected: false, collegeName: 'Rensselaer Polytechnic Institute'},
  {index: 584, selected: false, collegeName: 'Radford University'},
  {index: 585, selected: false, collegeName: 'Rutgers, The State University of New Jersey'},
  {index: 586, selected: false, collegeName: 'Roger Williams University'},
  {index: 587, selected: false, collegeName: 'Sacred Heart University Connecticut'},
  {index: 588, selected: false, collegeName: 'The Sage Colleges'},
  {index: 589, selected: false, collegeName: 'Saint Joseph\'s College (Indiana)'},
  {index: 590, selected: false, collegeName: 'Saint Mary\'s College'},
  {index: 591, selected: false, collegeName: 'Samford University'},
  {index: 592, selected: false, collegeName: 'St. Andrews University'},
  {index: 593, selected: false, collegeName: 'St. Ambrose University'},
  {index: 594, selected: false, collegeName: 'Sweet Briar College'},
  {index: 595, selected: false, collegeName: 'St. Bonaventure University'},
  {index: 596, selected: false, collegeName: 'Southwest Baptist University'},
  {index: 597, selected: false, collegeName: 'University of South Carolina'},
  {index: 598, selected: false, collegeName: 'Scripps College'},
  {index: 599, selected: false, collegeName: 'Southern Polytechnic State University'},
  {index: 600, selected: false, collegeName: 'Santa Clara University'},
  {index: 601, selected: false, collegeName: 'Sacramento City Unified School District'},
  {index: 602, selected: false, collegeName: 'South Dakota School of Mines and Technology'},
  {index: 603, selected: false, collegeName: 'South Dakota State University'},
  {index: 604, selected: false, collegeName: 'San Diego State University'},
  {index: 605, selected: false, collegeName: 'Seattle University'},
  {index: 606, selected: false, collegeName: 'Southeastern Louisiana University'},
  {index: 607, selected: false, collegeName: 'Southeast Missouri State University'},
  {index: 608, selected: false, collegeName: 'Sewane'},
  {index: 609, selected: false, collegeName: 'Stephen F. Austin State University'},
  {index: 610, selected: false, collegeName: 'Saint Francis University, Pennsylvania'},
  {index: 611, selected: false, collegeName: 'San Francisco State University'},
  {index: 612, selected: false, collegeName: 'Shawnee State University'},
  {index: 613, selected: false, collegeName: 'Spring Hill College'},
  {index: 614, selected: false, collegeName: 'Shippensburg University'},
  {index: 615, selected: false, collegeName: 'Shorter University'},
  {index: 616, selected: false, collegeName: 'Sam Houston State University'},
  {index: 617, selected: false, collegeName: 'Seton Hall University'},
  {index: 618, selected: false, collegeName: 'Simmons College'},
  {index: 619, selected: false, collegeName: 'Bard College at Simon\'s Rock'},
  {index: 620, selected: false, collegeName: 'Simpson College'},
  {index: 621, selected: false, collegeName: 'Southern Illinois University'},
  {index: 622, selected: false, collegeName: 'Southern Illinois University Edwardsville'},
  {index: 623, selected: false, collegeName: 'St. John\'s College'},
  {index: 624, selected: false, collegeName: 'St. John\'s College'},
  {index: 625, selected: false, collegeName: 'Saint Joseph\'s College of Maine'},
  {index: 626, selected: false, collegeName: 'St. John\'s College'},
  {index: 627, selected: false, collegeName: 'San Jose State University'},
  {index: 628, selected: false, collegeName: 'Saint Joseph\'s University'},
  {index: 629, selected: false, collegeName: 'Salish Kootenai College'},
  {index: 630, selected: false, collegeName: 'Skidmore College'},
  {index: 631, selected: false, collegeName: 'Penn State Schuylkill'},
  {index: 632, selected: false, collegeName: 'Sarah Lawrence College'},
  {index: 633, selected: false, collegeName: 'Saint Louis University'},
  {index: 634, selected: false, collegeName: 'Saint Michael\'s College'},
  {index: 635, selected: false, collegeName: 'Smith College'},
  {index: 636, selected: false, collegeName: 'Southwest Minnesota State University'},
  {index: 637, selected: false, collegeName: 'Southern Methodist University'},
  {index: 638, selected: false, collegeName: 'Saint Mary\'s University of Minnesota'},
  {index: 639, selected: false, collegeName: 'Southern New Hampshire University'},
  {index: 640, selected: false, collegeName: 'Southern Nazarene University'},
  {index: 641, selected: false, collegeName: 'Sonoma State University'},
  {index: 642, selected: false, collegeName: 'Southern Adventist University'},
  {index: 643, selected: false, collegeName: 'Southern West Virginia Community and Technical College'},
  {index: 644, selected: false, collegeName: 'Southwestern University'},
  {index: 645, selected: false, collegeName: 'Seattle Pacific University'},
  {index: 646, selected: false, collegeName: 'Slippery Rock University'},
  {index: 647, selected: false, collegeName: 'Stanford University'},
  {index: 648, selected: false, collegeName: 'South Texas College of Law'},
  {index: 649, selected: false, collegeName: 'St. Edward\'s University'},
  {index: 650, selected: false, collegeName: 'Stephens College'},
  {index: 651, selected: false, collegeName: 'Stetson University'},
  {index: 652, selected: false, collegeName: 'Stevens Institute of Technology'},
  {index: 653, selected: false, collegeName: 'University of St. Francis'},
  {index: 654, selected: false, collegeName: 'St. John\'s University'},
  {index: 655, selected: false, collegeName: 'St. Catherine University'},
  {index: 656, selected: false, collegeName: 'St. Lawrence University'},
  {index: 657, selected: false, collegeName: 'St. Louis College of Pharmacy'},
  {index: 658, selected: false, collegeName: 'Saint Martin\'s University'},
  {index: 659, selected: false, collegeName: 'Saint Mary\'s College of California'},
  {index: 660, selected: false, collegeName: 'Stockton College'},
  {index: 661, selected: false, collegeName: 'St. Olaf College'},
  {index: 662, selected: false, collegeName: 'Strayer University'},
  {index: 663, selected: false, collegeName: 'The College of Saint Rose'},
  {index: 664, selected: false, collegeName: 'University of St. Thomas'},
  {index: 665, selected: false, collegeName: 'University of St. Thomas'},
  {index: 666, selected: false, collegeName: 'Saint Thomas University'},
  {index: 667, selected: false, collegeName: 'Saint Vincent College'},
  {index: 668, selected: false, collegeName: 'Shenandoah University'},
  {index: 669, selected: false, collegeName: 'Southern University and Agricultural and Mechanical College'},
  {index: 670, selected: false, collegeName: 'Suffolk University'},
  {index: 671, selected: false, collegeName: 'Sul Ross State University'},
  {index: 672, selected: false, collegeName: 'State University of New York Institute of Technology'},
  {index: 673, selected: false, collegeName: 'Stony Brook University'},
  {index: 674, selected: false, collegeName: 'Susquehanna University'},
  {index: 675, selected: false, collegeName: 'Southern Utah University'},
  {index: 676, selected: false, collegeName: 'Saginaw Valley State University'},
  {index: 677, selected: false, collegeName: 'Swarthmore College'},
  {index: 678, selected: false, collegeName: 'Saint Xavier University'},
  {index: 679, selected: false, collegeName: 'Syracuse University'},
  {index: 680, selected: false, collegeName: 'Thunderbird School of Global Management'},
  {index: 681, selected: false, collegeName: 'Tabor College'},
  {index: 682, selected: false, collegeName: 'William Howard Taft University'},
  {index: 683, selected: false, collegeName: 'Taft University System'},
  {index: 684, selected: false, collegeName: 'Texas A&M International University'},
  {index: 685, selected: false, collegeName: 'Texas A&M University'},
  {index: 686, selected: false, collegeName: 'Texas A&M University Corpus Christi'},
  {index: 687, selected: false, collegeName: 'Tarleton State University'},
  {index: 688, selected: false, collegeName: 'Taylor University'},
  {index: 689, selected: false, collegeName: 'Teachers College Columbia University'},
  {index: 690, selected: false, collegeName: 'Texas Christian University'},
  {index: 691, selected: false, collegeName: 'Temple University'},
  {index: 692, selected: false, collegeName: 'Thomas Edison State College'},
  {index: 693, selected: false, collegeName: 'University of Sioux Falls'},
  {index: 694, selected: false, collegeName: 'Thomas College'},
  {index: 695, selected: false, collegeName: 'Thomas More College'},
  {index: 696, selected: false, collegeName: 'Thomas Jefferson University'},
  {index: 697, selected: false, collegeName: 'Tennessee State University'},
  {index: 698, selected: false, collegeName: 'Tennessee Technological University'},
  {index: 699, selected: false, collegeName: 'Towson University'},
  {index: 700, selected: false, collegeName: 'Transylvania University'},
  {index: 701, selected: false, collegeName: 'Trinity College'},
  {index: 702, selected: false, collegeName: 'Trinity University'},
  {index: 703, selected: false, collegeName: 'Truman State University'},
  {index: 704, selected: false, collegeName: 'Texas Southern University'},
  {index: 705, selected: false, collegeName: 'Texas Tech University'},
  {index: 706, selected: false, collegeName: 'Texas Tech University Health Sciences Center'},
  {index: 707, selected: false, collegeName: 'Tufts University'},
  {index: 708, selected: false, collegeName: 'Union Institute & University'},
  {index: 709, selected: false, collegeName: 'Tulane University'},
  {index: 710, selected: false, collegeName: 'Texas Woman\'s University'},
  {index: 711, selected: false, collegeName: 'The University of Alabama'},
  {index: 712, selected: false, collegeName: 'University of Alaska Anchorage'},
  {index: 713, selected: false, collegeName: 'The University of Alabama at Birmingham'},
  {index: 714, selected: false, collegeName: 'The University of Alabama in Huntsville'},
  {index: 715, selected: false, collegeName: 'The University of Akron'},
  {index: 716, selected: false, collegeName: 'University of Arkansas at Little Rock'},
  {index: 717, selected: false, collegeName: 'University of Arkansas at Monticello'},
  {index: 718, selected: false, collegeName: 'University of Arkansas for Medical Sciences'},
  {index: 719, selected: false, collegeName: 'University of Arkansas'},
  {index: 720, selected: false, collegeName: 'The University of Baltimore'},
  {index: 721, selected: false, collegeName: 'University of Cincinnati'},
  {index: 722, selected: false, collegeName: 'University of Central Arkansas'},
  {index: 723, selected: false, collegeName: 'University of Colorado Colorado Springs'},
  {index: 724, selected: false, collegeName: 'University of California, Davis'},
  {index: 725, selected: false, collegeName: 'University of Central Florida'},
  {index: 726, selected: false, collegeName: 'The University of Chicago'},
  {index: 727, selected: false, collegeName: 'University of California, Irvine'},
  {index: 728, selected: false, collegeName: 'University of California, Los Angeles'},
  {index: 729, selected: false, collegeName: 'University of Central Missouri'},
  {index: 730, selected: false, collegeName: 'University of Connecticut'},
  {index: 731, selected: false, collegeName: 'University of California, Riverside'},
  {index: 732, selected: false, collegeName: 'University of California, Santa Barbara'},
  {index: 733, selected: false, collegeName: 'University of California, Santa Cruz'},
  {index: 734, selected: false, collegeName: 'University of California, San Diego'},
  {index: 735, selected: false, collegeName: 'University of California, San Francisco'},
  {index: 736, selected: false, collegeName: 'University of Dallas'},
  {index: 737, selected: false, collegeName: 'University of Dayton'},
  {index: 738, selected: false, collegeName: 'University of the District of Columbia'},
  {index: 739, selected: false, collegeName: 'University of Delaware'},
  {index: 740, selected: false, collegeName: 'University of Detroit Mercy'},
  {index: 741, selected: false, collegeName: 'University of Florida'},
  {index: 742, selected: false, collegeName: 'University Of Georgia'},
  {index: 743, selected: false, collegeName: 'University of Great Falls'},
  {index: 744, selected: false, collegeName: 'University of Houston'},
  {index: 745, selected: false, collegeName: 'University of Hawaii at Hilo'},
  {index: 746, selected: false, collegeName: 'University of Illinois at Chicago'},
  {index: 747, selected: false, collegeName: 'University of Idaho'},
  {index: 748, selected: false, collegeName: 'University of Indianapolis'},
  {index: 749, selected: false, collegeName: 'The University of Iowa'},
  {index: 750, selected: false, collegeName: 'Upper Iowa University'},
  {index: 751, selected: false, collegeName: 'University of Illinois at Urbana-Champaign'},
  {index: 752, selected: false, collegeName: 'University of Kentucky'},
  {index: 753, selected: false, collegeName: 'University of Massachusetts Amherst'},
  {index: 754, selected: false, collegeName: 'University of Massachusetts Dartmouth'},
  {index: 755, selected: false, collegeName: 'University of Massachusetts'},
  {index: 756, selected: false, collegeName: 'University of Maryland, Baltimore County'},
  {index: 757, selected: false, collegeName: 'University of Mississippi Medical Center'},
  {index: 758, selected: false, collegeName: 'University of Maryland'},
  {index: 759, selected: false, collegeName: 'University of Michigan-Dearborn'},
  {index: 760, selected: false, collegeName: 'University of Maine Farmington'},
  {index: 761, selected: false, collegeName: 'University of Maine at Fort Kent'},
  {index: 762, selected: false, collegeName: 'University of Michigan'},
  {index: 763, selected: false, collegeName: 'University of Missouri, Kansas City'},
  {index: 764, selected: false, collegeName: 'University of Massachusetts, Lowell'},
  {index: 765, selected: false, collegeName: 'University of Maine at Machias'},
  {index: 766, selected: false, collegeName: 'University of Minnesota'},
  {index: 767, selected: false, collegeName: 'University of Missouri-St. Louis'},
  {index: 768, selected: false, collegeName: 'University of Mississippi Medical Center'},
  {index: 769, selected: false, collegeName: 'University of Montana'},
  {index: 770, selected: false, collegeName: 'University of Maryland University College'},
  {index: 771, selected: false, collegeName: 'The University of North Carolina at Chapel Hill'},
  {index: 772, selected: false, collegeName: 'The University of North Carolina at Asheville'},
  {index: 773, selected: false, collegeName: 'The University of North Carolina at Charlotte'},
  {index: 774, selected: false, collegeName: 'The University of North Carolina at Greensboro'},
  {index: 775, selected: false, collegeName: 'The University of North Carolina at Wilmington'},
  {index: 776, selected: false, collegeName: 'The University of North Dakota'},
  {index: 777, selected: false, collegeName: 'University of New England'},
  {index: 778, selected: false, collegeName: 'University of North Florida'},
  {index: 779, selected: false, collegeName: 'University of New Hampshire'},
  {index: 780, selected: false, collegeName: 'University of Northern Iowa'},
  {index: 781, selected: false, collegeName: 'Union College'},
  {index: 782, selected: false, collegeName: 'University of Northern Colorado'},
  {index: 783, selected: false, collegeName: 'University of Nebraska at Kearney'},
  {index: 784, selected: false, collegeName: 'University of Nebraska-Lincoln'},
  {index: 785, selected: false, collegeName: 'University of Nevada, Las Vegas'},
  {index: 786, selected: false, collegeName: 'The University of New Mexico'},
  {index: 787, selected: false, collegeName: 'University of New Orleans'},
  {index: 788, selected: false, collegeName: 'University of Nebraska Omaha'},
  {index: 789, selected: false, collegeName: 'University of Nevada, Reno'},
  {index: 790, selected: false, collegeName: 'University of North Texas'},
  {index: 791, selected: false, collegeName: 'The University of Scranton'},
  {index: 792, selected: false, collegeName: 'University of Guam'},
  {index: 793, selected: false, collegeName: 'University of the Pacific'},
  {index: 794, selected: false, collegeName: 'University of Oregon'},
  {index: 795, selected: false, collegeName: 'University of Pennsylvania'},
  {index: 796, selected: false, collegeName: 'University of Puget Sound'},
  {index: 797, selected: false, collegeName: 'University of Rhode Island'},
  {index: 798, selected: false, collegeName: 'University of Richmond'},
  {index: 799, selected: false, collegeName: 'Ursinus College'},
  {index: 800, selected: false, collegeName: 'University of Science and Arts of Oklahoma'},
  {index: 801, selected: false, collegeName: 'University of Southern California'},
  {index: 802, selected: false, collegeName: 'The University of South Dakota'},
  {index: 803, selected: false, collegeName: 'University of South Florida'},
  {index: 804, selected: false, collegeName: 'University of San Francisco'},
  {index: 805, selected: false, collegeName: 'University System of Georgia'},
  {index: 806, selected: false, collegeName: 'University of Southern Indiana'},
  {index: 807, selected: false, collegeName: 'Alliant International University'},
  {index: 808, selected: false, collegeName: 'The University of Southern Mississippi'},
  {index: 809, selected: false, collegeName: 'University of Southern Maine'},
  {index: 810, selected: false, collegeName: 'West Point'},
  {index: 811, selected: false, collegeName: 'U.S. Merchant Marine Academy'},
  {index: 812, selected: false, collegeName: 'University of South Alabama'},
  {index: 813, selected: false, collegeName: 'Utah State University'},
  {index: 814, selected: false, collegeName: 'The University of Texas at Arlington'},
  {index: 815, selected: false, collegeName: 'The University of Utah'},
  {index: 816, selected: false, collegeName: 'The University of Tampa'},
  {index: 817, selected: false, collegeName: 'The University of Texas at Brownsville'},
  {index: 818, selected: false, collegeName: 'The University of Texas at Dallas'},
  {index: 819, selected: false, collegeName: 'The University of Texas at El Paso'},
  {index: 820, selected: false, collegeName: 'The University of Texas at Austin'},
  {index: 821, selected: false, collegeName: 'The University of Texas Health Science Center'},
  {index: 822, selected: false, collegeName: 'UT Health Northeast'},
  {index: 823, selected: false, collegeName: 'The University of Texas Health Science Center at San Antonio'},
  {index: 824, selected: false, collegeName: 'The University of Tennessee, Knoxville'},
  {index: 825, selected: false, collegeName: 'The University of Tennessee at Martin'},
  {index: 826, selected: false, collegeName: 'The University of Texas Medical Branch'},
  {index: 827, selected: false, collegeName: 'The University of Toledo'},
  {index: 828, selected: false, collegeName: 'The University of Texas at San Antonio'},
  {index: 829, selected: false, collegeName: 'University of Texas System'},
  {index: 830, selected: false, collegeName: 'University of Tulsa'},
  {index: 831, selected: false, collegeName: 'Union University'},
  {index: 832, selected: false, collegeName: 'University of the Virgin Islands'},
  {index: 833, selected: false, collegeName: 'The University of Vermont'},
  {index: 834, selected: false, collegeName: 'The University of West Alabama'},
  {index: 835, selected: false, collegeName: 'University of Wisconsin-Eau Claire'},
  {index: 836, selected: false, collegeName: 'University of West Florida'},
  {index: 837, selected: false, collegeName: 'University of Wisconsin, Green Bay'},
  {index: 838, selected: false, collegeName: 'University of Wisconsin, La Crosse'},
  {index: 839, selected: false, collegeName: 'University of Wisconsin, Milwaukee'},
  {index: 840, selected: false, collegeName: 'University of Wisconsin, Oshkosh'},
  {index: 841, selected: false, collegeName: 'University Of Wisconsin, Parkside'},
  {index: 842, selected: false, collegeName: 'University of Wisconsin, Platteville'},
  {index: 843, selected: false, collegeName: 'University of Wisconsin, River Falls'},
  {index: 844, selected: false, collegeName: 'University of Wisconsin, Madison'},
  {index: 845, selected: false, collegeName: 'University of Wisconsin, Stevens Point'},
  {index: 846, selected: false, collegeName: 'University of Wisconsin, Stout'},
  {index: 847, selected: false, collegeName: 'University of Wisconsin, Superior'},
  {index: 848, selected: false, collegeName: 'University of Wisconsin, Whitewater'},
  {index: 849, selected: false, collegeName: 'University of Wyoming'},
  {index: 850, selected: false, collegeName: 'Valparaiso University'},
  {index: 851, selected: false, collegeName: 'Washington State University Vancouver'},
  {index: 852, selected: false, collegeName: 'Vanderbilt University'},
  {index: 853, selected: false, collegeName: 'Vassar College'},
  {index: 854, selected: false, collegeName: 'Virginia Commonwealth University'},
  {index: 855, selected: false, collegeName: 'Virginia Intermont College'},
  {index: 856, selected: false, collegeName: 'The University of Virginia'},
  {index: 857, selected: false, collegeName: 'Virginia Military Institute'},
  {index: 858, selected: false, collegeName: 'Virginia State University'},
  {index: 859, selected: false, collegeName: 'Virginia Tech'},
  {index: 860, selected: false, collegeName: 'Vermont Tech'},
  {index: 861, selected: false, collegeName: 'Virginia Wesleyan College'},
  {index: 862, selected: false, collegeName: 'Wabash College'},
  {index: 863, selected: false, collegeName: 'Walden University'},
  {index: 864, selected: false, collegeName: 'Warren Wilson College'},
  {index: 865, selected: false, collegeName: 'Wartburg College'},
  {index: 866, selected: false, collegeName: 'Washington College'},
  {index: 867, selected: false, collegeName: 'University of Washington'},
  {index: 868, selected: false, collegeName: 'Wayne State University'},
  {index: 869, selected: false, collegeName: 'Westminster College in Salt Lake City, Utah'},
  {index: 870, selected: false, collegeName: 'Western Carolina University'},
  {index: 871, selected: false, collegeName: 'West Chester University'},
  {index: 872, selected: false, collegeName: 'Weber State University'},
  {index: 873, selected: false, collegeName: 'Webster University'},
  {index: 874, selected: false, collegeName: 'Wellesley College'},
  {index: 875, selected: false, collegeName: 'Wells College'},
  {index: 876, selected: false, collegeName: 'Wesley College'},
  {index: 877, selected: false, collegeName: 'Wesleyan University'},
  {index: 878, selected: false, collegeName: 'The University of West Alabama'},
  {index: 879, selected: false, collegeName: 'The University of West Georgia'},
  {index: 880, selected: false, collegeName: 'Westminster College'},
  {index: 881, selected: false, collegeName: 'Westminster College'},
  {index: 882, selected: false, collegeName: 'Westmont College'},
  {index: 883, selected: false, collegeName: 'Wake Forest University'},
  {index: 884, selected: false, collegeName: 'Wheaton College'},
  {index: 885, selected: false, collegeName: 'Wheaton College, Norton, Massachusetts'},
  {index: 886, selected: false, collegeName: 'Whitman College'},
  {index: 887, selected: false, collegeName: 'Whittier College'},
  {index: 888, selected: false, collegeName: 'Whitworth University'},
  {index: 889, selected: false, collegeName: 'Widener University'},
  {index: 890, selected: false, collegeName: 'Wilberforce University'},
  {index: 891, selected: false, collegeName: 'Wilkes University'},
  {index: 892, selected: false, collegeName: 'Willamette University'},
  {index: 893, selected: false, collegeName: 'Williams College'},
  {index: 894, selected: false, collegeName: 'Wilmington College of Ohio'},
  {index: 895, selected: false, collegeName: 'Winthrop University'},
  {index: 896, selected: false, collegeName: 'University of Wisconsin-Madison'},
  {index: 897, selected: false, collegeName: 'Wentworth Institute of Technology'},
  {index: 898, selected: false, collegeName: 'Wittenberg University'},
  {index: 899, selected: false, collegeName: 'Western Illinois University'},
  {index: 900, selected: false, collegeName: 'Western Kentucky University'},
  {index: 901, selected: false, collegeName: 'Washington and Lee University'},
  {index: 902, selected: false, collegeName: 'The College of William & Mary'},
  {index: 903, selected: false, collegeName: 'Western Michigan University'},
  {index: 904, selected: false, collegeName: 'William Mitchell College of Law'},
  {index: 905, selected: false, collegeName: 'William Penn University'},
  {index: 906, selected: false, collegeName: 'Western New Mexico University'},
  {index: 907, selected: false, collegeName: 'Wofford College'},
  {index: 908, selected: false, collegeName: 'The College of Wooster'},
  {index: 909, selected: false, collegeName: 'Worcester Polytechnic Institute'},
  {index: 910, selected: false, collegeName: 'Wright State University'},
  {index: 911, selected: false, collegeName: 'Westfield State University'},
  {index: 912, selected: false, collegeName: 'Washington State University'},
  {index: 913, selected: false, collegeName: 'West Texas A&M University'},
  {index: 914, selected: false, collegeName: 'Westminster Theological Seminary'},
  {index: 915, selected: false, collegeName: 'Washington University in St. Louis'},
  {index: 916, selected: false, collegeName: 'West Virginia Network for Educational Telecomputing'},
  {index: 917, selected: false, collegeName: 'West Virginia School of Osteopathic Medicine'},
  {index: 918, selected: false, collegeName: 'West Virginia University'},
  {index: 919, selected: false, collegeName: 'Western Washington University'},
  {index: 920, selected: false, collegeName: 'Xavier University of Louisiana'},
  {index: 921, selected: false, collegeName: 'Yale University'},
  {index: 922, selected: false, collegeName: 'York College of Pennsylvania'},
  {index: 923, selected: false, collegeName: 'Youngstown State University'},
  {index: 924, selected: false, collegeName: 'Yeshiva University'},
],
selectedColleges: [],
filter: ''
}
